#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov 10 14:34:38 2025

@author: jane
"""
import pandas as pd
import pickle
import numpy as np

from preprocessing import remove_outliers
from sklearn.decomposition import PCA
from sklearn.compose import ColumnTransformer

def feature_preperation(features_train_soil, features_test_soil, 
                        target_train_soil, target_test_soil,
                        features_train_met, features_test_met,
                        target_train_met, target_test_met,
                        model_soil):
    '''
    Prepare features for meteorological model by removing outliers, adding target 
    predictions generated by soil model and running a pca over the wind and 
    temperature features respectively. Then split features into four geographic
    regions and pickle results.

    Parameters
    ----------
    features_train_soil : pd.DataFrame
    features_test_soil : pd.DataFrame
    target_train_soil : 1D pd.DataFrame
    target_test_soil : 1D pd.DataFrame
    features_train_met : pd.DataFrame
    features_test_met : pd.DataFrame
    target_train_met : 1D pd.DataFrame
    target_test_met : 1D pd.DataFrame
    model_soil : trained sklearn model
        sklearn regressor model trained on features_train_soil.

    Returns
    -------
    None.

    '''
    #remove outliers from training data and generate soil predictions-----------
    
    features_soil = pd.concat([features_train_soil, features_test_soil])
    features_train_soil, features_train_met, target_train_soil, target_train_met = remove_outliers(features_train_soil,
                                                                                                   features_train_met,
                                                                                                   target_train_soil, 
                                                                                                   target_train_met)
    
    #run model on all soil data, including outliers, because we need this later
    #for testing meteorological data that includes outlying fips
    target_soil_pred = model_soil.predict(features_soil)
    target_soil_pred = pd.DataFrame(target_soil_pred, index = features_soil.index)
    
    #met features---------------------------------------------------------------
    
    #add drought predictions from soil model to meteorological data
    target_soil_pred_ext_for_train = []
    target_soil_pred_ext_for_test = []
    
    for fips in features_train_met.fips.unique():
        target_soil_pred_ext_for_train.extend([target_soil_pred.loc[fips, 0]]*len(features_train_met[features_train_met['fips'] == fips]))
    
    for fips in features_test_met.fips.unique():   
        target_soil_pred_ext_for_test.extend([target_soil_pred.loc[fips, 0]]*len(features_test_met[features_test_met['fips'] == fips]))
    
    features_train_met['pred_drought'] = target_soil_pred_ext_for_train
    features_test_met['pred_drought'] = target_soil_pred_ext_for_test
    
    #split dates into day month and year and drop date column
    features_train_met['month'] = features_train_met.date.dt.month.astype('int')
    features_train_met['day'] = features_train_met.date.dt.day.astype('int')
    features_train_met['year'] = features_train_met.date.dt.year.astype('int')
    features_train_met = features_train_met.drop('date', axis = 1)
    
    features_test_met['month'] = features_test_met.date.dt.month.astype('int')
    features_test_met['day'] = features_test_met.date.dt.day.astype('int')
    features_test_met['year'] = features_test_met.date.dt.year.astype('int')
    features_test_met = features_test_met.drop('date', axis = 1)
    
    #run pca on highly correlated columns, one on temperature and one on wind
    features_train_met = wind_temp_pca(features_train_met, target_train_met)
    
    pd.to_pickle(features_train_met, path_met + 'features_met_train_prepared.p')
    pd.to_pickle(features_test_met, path_met + 'features_met_test_prepared.p')
    pd.to_pickle(target_train_met, path_met + 'target_met_train_prepared.p')
    pd.to_pickle(target_test_met, path_met + 'target_met_test_prepared.p')
    
    #split by region and save seperately----------------------------------------
    regions = {'west' : [4, 6, 8, 16, 30, 32, 35, 41, 49, 53, 56],
               'south' : [1, 5, 10, 11, 12, 13, 21, 22, 24, 28, 37, 40, 45, 47, 48, 51, 54],
               'midwest' : [17, 18, 19, 20, 26, 27, 29, 31, 38, 39, 46, 55],
               'east' : [9, 23, 25, 33, 34, 36, 42, 44, 50]}
    #target_train = target_train.reindex()
    #features_test_met = features_test_met.reindex()
    for region in regions.keys():
        region_fips_list = []
        for state in regions[region]:
            region_fips_list.extend(features_soil[(features_soil.index >= 1000*state) & (features_soil.index < 1000*(state + 1))].index)
        features_train_region = features_train_met[features_train_met['fips'].isin(region_fips_list)]
        features_test_region = features_test_met[features_test_met['fips'].isin(region_fips_list)]
        target_train_region = target_train_met[features_train_met['fips'].isin(region_fips_list)]
        target_test_region = target_test_met[features_test_met['fips'].isin(region_fips_list)]
        pd.to_pickle(features_train_region, 
                     path_met + 'features_train_met_prep_{}.p'.format(region))
        pd.to_pickle(features_test_region, 
                     path_met + 'features_test_met_prep_{}.p'.format(region))
        pd.to_pickle(target_train_region, 
                     path_met + 'target_train_met_prep_{}.p'.format(region))
        pd.to_pickle(target_test_region, 
                     path_met + 'target_test_met_prep_{}.p'.format(region))
    
    return

def wind_temp_pca(features, target, n_comp = 0.95):
    temp_cols = ['QV2M', 'T2M', 'T2MDEW', 'T2MWET', 'T2M_MAX', 'T2M_MIN', 'TS']
    wind_cols = ['WS10M', 'WS10M_MAX', 'WS10M_MIN', 'WS10M_RANGE', 'WS50M',
                    'WS50M_MAX', 'WS50M_MIN', 'WS50M_RANGE']
    
    pca_temp = PCA(n_components = n_comp)
    pca_wind = PCA(n_components = n_comp)
    col_pca = ColumnTransformer([('pca_temp', pca_temp, temp_cols),
                                 ('pca_wind', pca_wind, wind_cols)],
                                remainder = 'passthrough')
    col_pca.fit(features)
    
    n_components = (len(col_pca.named_transformers_['pca_temp'].explained_variance_ratio_) +
                    len(col_pca.named_transformers_['pca_wind'].explained_variance_ratio_))
    pca_names = ['PCA_comp_' + str(i) for i in range(n_components)]
    
    important_features_temp = get_important_components(col_pca.named_transformers_['pca_temp'],
                                                     temp_cols)
    important_features_wind = get_important_components(col_pca.named_transformers_['pca_wind'],
                                                       wind_cols)
    print(important_features_temp)
    print(important_features_wind)
    remaining_names = features.columns[col_pca._remainder[2]]
    features = pd.DataFrame(col_pca.transform(features),
                                  columns = list(pca_names)+ list(remaining_names),
                                  index = target.index)
    pickle.dump(col_pca, 
                open('/home/jane/Documents/Weiterbildung/DPP/portfolio_project/scripts/models/trained_model_soil.p',
                     'wb'))
    return features

def get_important_components(model, feature_names):
    
    '''
    Returns features names of important components from PCA
    Parameters:
        model : fitted pca model
        feature_names : list of features that go into PCA
    Returns: 
        most_important_names : list of most important feature names
    '''
    # number of components
    n_pcs= model.components_.shape[0]
    # get the index of the most important feature on EACH component
    most_important = [np.abs(model.components_[i]).argmax() for i in range(n_pcs)]
    # get the names
    most_important_names = [feature_names[most_important[i]] for i in range(n_pcs)]
    
    return most_important_names
        
if __name__ == '__main__':
    path_soil = '/home/jane/Documents/Weiterbildung/DPP/portfolio_project/data/processed/soil/'
    features_train_soil = pd.read_pickle(path_soil + 'features_train_soil.p')
    target_train_soil = pd.read_pickle(path_soil + 'target_train_soil.p')
    features_test_soil = pd.read_pickle(path_soil + 'features_test_soil.p')
    target_test_soil = pd.read_pickle(path_soil + 'target_test_soil.p')
    
    path_met = '/home/jane/Documents/Weiterbildung/DPP/portfolio_project/data/processed/met/'
    features_train_met = pd.read_pickle(path_met + 'features_train_concat.p')
    target_train_met = pd.read_pickle(path_met + 'target_train_concat.p')
    features_test_met = pd.read_pickle(path_met + 'features_test_concat.p')
    target_test_met = pd.read_pickle(path_met + 'target_test_concat.p')
    
    model_soil = pickle.load(open('/home/jane/Documents/Weiterbildung/DPP/portfolio_project/scripts/models/trained_model_soil.p', 'rb'))
    
    feature_preperation(features_train_soil, features_test_soil, 
                            target_train_soil, target_test_soil,
                            features_train_met, features_test_met,
                            target_train_met, target_test_met,
                            model_soil)